# This is a basic workflow to help you get started with Actions

name: Deploy to Raspberry Pi

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-brains:
    # The type of runner that the job will run on
    runs-on: [self-hosted, Brains]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup virtual env, install dependencies
      - name: Build brains containers
        run: |
          cd brain
          docker compose build
  deploy-brains:
    runs-on: [self-hosted, Brains]
    needs: build-brains
    
    steps:
      - name: Kill running compose
        run: |
          cd brain
          docker compose down
      # Run gunicorn server
      - name: Run docker compose
        run: |
          cd brain
          docker compose up -d